apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-helm
spec:
  destination:
    namespace: user1-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: documentation/modules/ROOT/examples/bgd-helm-chart
    repoURL: 'https://github.com/OpenShiftDemos/openshift-gitops-workshop'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true